### ISSUE TITLE
snap refresh on rpi causes kernel crash

### ISSUE THREAD

**Issue by bmpotter** [open-horizon/bluehorizon-snap#18]
I ran `snap refresh --devmode --edge bluehorizon` on my rpi to pick up the latest snap. It downloaded the new snap, and sometime after displaying `[|] Mount snap "bluehorizon" (53)` it threw me into kdb on the console. After rebooting, the new snap seems to be working ok. Ling saw the same result.

**Comment by bmpotter** [comment]
Carl says snap refresh works on x84

**Comment by linggao** [comment]
Kernel panic output on a rpi3.
[336032.404195] Unable to handle kernel NULL pointer dereference at virtual address 00000008
[336032.417227] pgd = b66fc000
[336032.422448] [00000008] *pgd=21359831, *pte=00000000, *ppte=00000000
[336032.432174] Internal error: Oops: 17 [#1] SMP ARM

Entering kdb (current=0xa11aca40, pid 7068) on processor 0 Oops: (null)
due to oops @ 0x802dad7c
CPU: 0 PID: 7068 Comm: mount Not tainted 4.4.0-1009-raspi2 #10-Ubuntu
Hardware name: BCM2709
task: a11aca40 ti: a7d5e000 task.ti: a7d5e000
PC is at propagate_one+0xc4/0x1b0
LR is at 0xb8be6f00
pc : [<802dad7c>]    lr : [<b8be6f00>]    psr: 800d0013
sp : a7d5fe40  ip : 000000de  fp : a7d5fe5c
r10: 00000000  r9 : a1245cc0  r8 : b8f2f300
r7 : a7d5fe88  r6 : 00000000  r5 : b8f2f300  r4 : 81041f98
r3 : 00000001  r2 : 00000000  r1 : b8f2f540  r0 : 00000000
Flags: Nzcv  IRQs on  FIQs on  Mode SVC_32  ISA ARM  Segment user
Control: 10c5383d  Table: 366fc06a  DAC: 00000055
CPU: 0 PID: 7068 Comm: mount Not tainted 4.4.0-1009-raspi2 #10-Ubuntu
Hardware name: BCM2709
[<80111f34>] (unwind_backtrace) from [<8010d198>] (show_stack+0x20/0x24)
[<8010d198>] (show_stack) from [<8055412c>] (dump_stack+0xc8/0x10c)
[<8055412c>] (dump_stack) from [<80109b3c>] (show_regs+0x1c/0x20)
[<80109b3c>] (show_regs) from [<801e36b0>] (kdb_main_loop+0x348/0x7b0)
[<801e36b0>] (kdb_main_loop) from [<801e6818>] (kdb_stub+0x2d0/0x528)
[<801e6818>] (kdb_stub) from [<801dbd30>] (kgdb_cpu_enter+0x460/0x7f0)
[<801dbd30>] (kgdb_cpu_enter) from [<801dc33c>] (kgdb_handle_exception+0x124/0x234)
[<801dc33c>] (kgdb_handle_exception) from [<80111234>] (kgdb_notify+0x40/0x90)
[<80111234>] (kgdb_notify) from [<80146528>] (notifier_call_chain+0x54/0x94)
[<80146528>] (notifier_call_chain) from [<801467d0>] (notify_die+0x58/0x78)
[<801467d0>] (notify_die) from [<8010d2c8>] (die+0x12c/0x498)
[<8010d2c8>] (die) from [<8011b520>] (__do_kernel_fault.part.0+0x74/0x1f4)
[<8011b520>] (__do_kernel_fault.part.0) from [<809ce190>] (do_page_fault+0x23c/0x3b8)
[<809ce190>] (do_page_fault) from [<80101230>] (do_DataAbort+0x58/0xe8)
[<80101230>] (do_DataAbort) from [<809cd7dc>] (__dabt_svc+0x3c/0x60)
Exception stack(0xa7d5fdf0 to 0xa7d5fe38)
fde0:                                     00000000 b8f2f540 00000000 00000001
fe00: 81041f98 b8f2f300 00000000 a7d5fe88 b8f2f300 a1245cc0 00000000 a7d5fe5c
fe20: 000000de a7d5fe40 b8be6f00 802dad7c 800d0013 ffffffff
[<809cd7dc>] (__dabt_svc) from [<802dad7c>] (propagate_one+0xc4/0x1b0)
[<802dad7c>] (propagate_one) from [<802db22c>] (propagate_mnt+0x128/0x154)
[<802db22c>] (propagate_mnt) from [<802cacb8>] (attach_recursive_mnt+0x16c/0x284)
[<802cacb8>] (attach_recursive_mnt) from [<802cae3c>] (graft_tree+0x6c/0x9c)
[<802cae3c>] (graft_tree) from [<802caf08>] (do_add_mount+0x9c/0xf0)
[<802caf08>] (do_add_mount) from [<802cbef4>] (do_mount+0x284/0xd70)
[<802cbef4>] (do_mount) from [<802ccdcc>] (SyS_mount+0xb4/0xf4)
[<802ccdcc>] (SyS_mount) from [<80108d00>] (ret_fast_syscall+0x0/0x1c)

**Comment by linggao** [comment]
Have submitted a Ubuntu bug report against snapd: https://bugs.launchpad.net/snapd/+bug/1664368

**Comment by linggao** [comment]
With the help from the ubuntu folks, I got the rpi2 upgraded to the latest kernel version 4.4.0-1042-raspi2, rebooted the it and the snap refresh works now.
Here is what I did to upgrade the kernel.
```apt-get update
apt-get upgrade
apt-get dist-upgrade
apt-get upgrade linux-firmware linux-firmware-raspi2 linux-headers-raspi2 linux-image-raspi2 linux-raspi2```
I will see how to get the latest kernel into out rpi image.

**Comment by linggao** [comment]
PR https://github.com/open-horizon/ubuntu-classic-image/pull/11

**Comment by linggao** [comment]
New images for rpi2 and 3 are built.  Need more testing.
